server:
  port: 8080


spring:

  datasource:

    # mysql
    #  driverClassName: com.mysql.jdbc.Driver
    #  url: jdbc:mysql://192.168.118.81:3306/zhdj_zzdx?useUnicode=true&characterEncoding=utf-8
    #  username: zhdj_zzdx
    #  password: zhdj_zzdxRj123.

    #oracle配置
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.118.78:1521:orcl
    username: CTIMS
    password: CTIMS


  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
dfish:
  database: oracle

